# Site settings
title: nathphan.me
description: Nathan's Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nathan Phan
user_description:
user_title: Software Developer
email: nathphan510@gmail.com
twitter_username:
github_username:  nathphan
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
